name: 'Kahn & Selesnick'
favicon: null
layout_spectrum: 0.8860869680065662
typography_spectrum: 0.3991158932913095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16375522804446518
  lightness: 0.17005382012575865
  saturation: 0.25866986019536853
  rhythmicContrast: 0.6693721867632121
purpose: []
